import { MutableRefObject, useRef } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import Highlights from "../components/Highlights";
import Features from "../components/Features";
import OurTeam from "../components/OurTeam";
import Timeline from "../components/Timeline";
import Contact from "../components/Contact";
import MailingList from "../components/MailingList";
import ChatSupport from "../components/ChatSupport";

const Home: NextPage = () => {
  const smoothScrollToDiv = (ref: MutableRefObject<HTMLInputElement>) =>
    ref.current.scrollIntoView({ behavior: "smooth", block: "start" });
  const scrollToDiv = (ref: MutableRefObject<HTMLInputElement>) =>
    window.scrollTo(0, ref.current.offsetTop);

  const elNav = useRef() as MutableRefObject<HTMLInputElement>;
  const elHighlights = useRef() as MutableRefObject<HTMLInputElement>;
  const elFeatures = useRef() as MutableRefObject<HTMLInputElement>;
  const elOurTeam = useRef() as MutableRefObject<HTMLInputElement>;
  const elContact = useRef() as MutableRefObject<HTMLInputElement>;

  return (
    <div>
      <Head>
        <title>Puzzoh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="images/puzzoh_logo.png" />
      </Head>

      <Navbar
        innerRef={elNav}
        clickHighlights={() => smoothScrollToDiv(elHighlights)}
        clickFeatures={() => smoothScrollToDiv(elFeatures)}
        clickOurTeam={() => smoothScrollToDiv(elOurTeam)}
        clickContact={() => smoothScrollToDiv(elContact)}
      />
      <Hero />
      <Highlights innerRef={elHighlights} />
      <Features innerRef={elFeatures} />
      <OurTeam innerRef={elOurTeam} />
      <Timeline />
      <MailingList innerRef={elContact} />
      <Contact />
      <ChatSupport />
    </div>
  );
};

export default Home;
