import { MutableRefObject, useRef } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import Features from "../components/Features";
import About from "../components/About";
import Timeline from "../components/Timeline";
import Download from "../components/Download";
import Contact from "../components/Contact";

const Home: NextPage = () => {
  const smoothScrollToDiv = (ref: MutableRefObject<HTMLInputElement>) =>
    ref.current.scrollIntoView({ behavior: "smooth", block: "start" });
  const scrollToDiv = (ref: MutableRefObject<HTMLInputElement>) =>
    window.scrollTo(0, ref.current.offsetTop);

  const elNav = useRef() as MutableRefObject<HTMLInputElement>;
  const elFeatures = useRef() as MutableRefObject<HTMLInputElement>;
  const elAbout = useRef() as MutableRefObject<HTMLInputElement>;
  const elTimeline = useRef() as MutableRefObject<HTMLInputElement>;
  const elDownload = useRef() as MutableRefObject<HTMLInputElement>;
  const elContact = useRef() as MutableRefObject<HTMLInputElement>;

  return (
    <div>
      <Head>
        <title>MEEToo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar
        reference={elNav}
        clickFeatures={() => smoothScrollToDiv(elFeatures)}
        clickTimeline={() => scrollToDiv(elTimeline)}
        clickDownload={() => scrollToDiv(elDownload)}
        clickContact={() => scrollToDiv(elContact)}
      />
      <Hero />
      <Features reference={elFeatures} />
      <div className="mockup-window border bg-base-300" ref={elTimeline}>
        <div className="flex justify-center px-4 py-16 bg-main">
          <div className="text-4xl font-bold flex flex-row justify-center items-center font-IndustrialSans">
            Our timeline
          </div>
          <Timeline />
        </div>
      </div>
      <div className="mockup-window border bg-base-300" ref={elDownload}>
        <div className="flex justify-center px-4 py-16 bg-first">
          <Download />
        </div>
      </div>
      <div ref={elContact}>
        <Contact />
      </div>
    </div>
  );
};

export default Home;
