import { MutableRefObject, useRef } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import Highlights from "../components/Highlights";
import Features from "../components/Features";
import OurTeam from "../components/OurTeam";
import Timeline from "../components/Timeline";
import Contact from "../components/Contact";
import MailingList from "../components/MailingList";

const Home: NextPage = () => {
  const smoothScrollToDiv = (ref: MutableRefObject<HTMLInputElement>) =>
    ref.current.scrollIntoView({ behavior: "smooth", block: "start" });
  const scrollToDiv = (ref: MutableRefObject<HTMLInputElement>) =>
    window.scrollTo(0, ref.current.offsetTop);

  const elNav = useRef() as MutableRefObject<HTMLInputElement>;
  const elHighlights = useRef() as MutableRefObject<HTMLInputElement>;
  const elFeatures = useRef() as MutableRefObject<HTMLInputElement>;
  const elOurTeam = useRef() as MutableRefObject<HTMLInputElement>;
  const elContact = useRef() as MutableRefObject<HTMLInputElement>;

  return (
    <div>
      <Head>
        <title>MEEToo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo1_transparent.png" />
      </Head>

      <Navbar
        reference={elNav}
        clickHighlights={() => smoothScrollToDiv(elHighlights)}
        clickFeatures={() => smoothScrollToDiv(elFeatures)}
        clickOurTeam={() => smoothScrollToDiv(elOurTeam)}
        clickContact={() => smoothScrollToDiv(elContact)}
      />
      <Hero />
      <Highlights reference={elHighlights} />
      <Features reference={elFeatures} />
      {/* <div className="mockup-window border bg-base-300" ref={elOurTeam}>
        <div className="flex justify-center px-4 py-16 bg-white"> */}
      {/* <div className="text-4xl font-bold flex flex-row justify-center items-center font-LexendDeca">
            Our timeline
          </div> */}
      <div ref={elOurTeam}>
        <OurTeam />
        <Timeline />
      </div>
      <div ref={elContact}>
        <MailingList />
        <Contact />
      </div>
    </div>
  );
};

export default Home;
